name: myenv
channels:
  - conda-forge
dependencies:
  - python=3.11
  - dlib
  - numpy
  - pillow
  - cmake
  - opencv
  - pip
  - pip:
      - fastapi
      - uvicorn
      - pydantic
      - requests
      - face_recognition
      - streamlit
