name: myenv
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pillow
  - cmake
  - pip
  - pip:
    - fastapi
    - uvicorn
    - pydantic
    - requests
    - dlib==19.21.1
    - face_recognition
    - opencv-python
    - streamlit
